### ISSUE TITLE
Error downloading mods while installing X-Life 2

### ISSUE THREAD

**Issue by oceanlover-yuno** [cdbbnnyCode/modpack-installer#23]
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2ec0fd49a0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='addons-ecs.forgesvc.net', port=443): Max retries exceeded with url: /api/v2/addon/388800 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec0fd49a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/install.py", line 207, in <module>
    main(args.zipfile, args.mcdir, args.forge_disable)
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/install.py", line 151, in main
    mods = mod_download.main(packdata_dir + '/manifest.json', '.modcache')
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/mod_download.py", line 96, in main
    loop.run_until_complete(future)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/mod_download.py", line 71, in download_mods_async
    for resp in await asyncio.gather(*tasks):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/mod_download.py", line 31, in fetch_mod
    project_info = get_json(session, api_url + ('/addon/%d' % pid))
  File "/home/user/Downloads/modpack-installer-2.2.1-beta/mod_download.py", line 21, in get_json
    r = session.get(url)
  File "/home/user/.local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='addons-ecs.forgesvc.net', port=443): Max retries exceeded with url: /api/v2/addon/388800 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec0fd49a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by cdbbnnyCode** [comment]
Looks like you're using an out-of-date version of the modpack installer (the latest is 2.3.0). CurseForge recently switched to a new API, so old versions of the installer do not work any more.

**Comment by oceanlover-yuno** [comment]
My bad! I downloaded from the releases page thinking I was getting the latest. I just cloned the repo and now it works great! Thank you.

**Comment by cdbbnnyCode** [comment]
Ah that makes sense, I haven't been tagging the releases lately. Glad that sorted it out!
