### ISSUE TITLE
Doesn't is works with Java 16?

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [cdbbnnyCode/modpack-installer#5]
I have Java 16 but it shows this error 
```
Extracting Crucial2-1.3.3.zip
Creating .minecraft directory
Creating symlinks
Creating launcher profiles
Installing modloader
Downloading https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar
Status: 200
Traceback (most recent call last):
  File "/home/kushagra/Desktop/modpack-installer-master/install.py", line 196, in <module>
    main(args.zipfile, args.forge_disable)
  File "/home/kushagra/Desktop/modpack-installer-master/install.py", line 125, in main
    modloaders[modloader](manifest, mcver, mlver, packname, mc_dir, manual)
  File "/home/kushagra/Desktop/modpack-installer-master/forge_install.py", line 29, in main
    subprocess.run(['javac', 'ForgeHack.java'])
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'javac'
```

**Comment by cdbbnnyCode** [comment]
Yes it should; however, you need the Java Development Kit (not just a JRE), as this tool needs to invoke the Java compiler.

Also, the JDK binaries (`/usr/lib/jvm/{jdk name}/bin`) need to be in your PATH; otherwise, this program will fail.

On a third note, automatic Forge installation only works for certain 1.12.2 Forge versions. I'd recommend using the `--manual` flag and setting the path manually.

**Comment by Kushagra-Srivastava** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
