### ISSUE TITLE
Error when downloading modpacks 

### ISSUE THREAD

**Issue by cdbbnnyCode** [cdbbnnyCode/modpack-installer#9]
I got one step closer by selecting the "correct" directory in the dialog that opens with the `--manual` option. It needs to be `pack/<yourpack>/.minecraft`.

It downloads the addons, but then fails with another error:

```
Traceback (most recent call last):
  File "/home/jreimann/apps/modpack-installer/install.py", line 196, in <module>
    main(args.zipfile, args.forge_disable)
  File "/home/jreimann/apps/modpack-installer/install.py", line 140, in main
    mods = mod_download.main(packdata_dir + '/manifest.json', '.modcache')
  File "/home/jreimann/apps/modpack-installer/mod_download.py", line 70, in main
    loop.run_until_complete(future)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/jreimann/apps/modpack-installer/mod_download.py", line 56, in download_mods_async
    for resp in await asyncio.gather(*tasks):
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jreimann/apps/modpack-installer/mod_download.py", line 32, in fetch_mod
    file_type = project_info['websiteUrl'].split('/')[4] # mc-mods or texture-packs
TypeError: 'NoneType' object is not subscriptable
```

_Originally posted by @ctron in https://github.com/cdbbnnyCode/modpack-installer/issues/8#issuecomment-1008078832_

**Comment by cdbbnnyCode** [comment]
It appears that the Forge API occasionally returns 504 gateway timeout errors. Fixed in v2.2-beta.
